### PR TITLE
Add support of stream input

### PR DESCRIPTION
**Pull request by LoicMahieu**
I added some tests for consolidate the support of stream input.

### CODE REVIEW

**Comment by LoicMahieu** [comment]
Hi @devongovett 
Are you still maintaining the project ? If you lack time and you are interested, I will be delighted to assist in the maintenance of the project, like reviewing issues and PR. This project is some quite important in a few of mine projects.
I think there is some PR proposed that are really interesting.

**Comment by LoicMahieu** [comment]
@zxlin It seems you are contributor of this project. I hope you will have time to review this PR asap.
If you don't have time for maintaining the project, I will be happy to assist you. Please contact me.

**Comment by zxlin** [comment]
@LoicMahieu Hey, I'd be happy to add this in. There's currently some conflicts that looks a little nasty to resolve. 

Could you fork the latest master branch and submit a PR with a single commit?

**Comment by LoicMahieu** [comment]
@zxlin Rebase done!

**Comment by LoicMahieu** [comment]
Fixed supports of node 0.10 and 0.12
---
@zxlin @devongovett This project is heavily used in my company. We are open to help in the maintenance of this project. Ping me if you are interested.

**Comment by zxlin** [comment]
@LoicMahieu can you also contribute some test cases to the specs so that we can make sure the stream input component doesn't get broken with future changes.

**Comment by LoicMahieu** [comment]
Is this not already done ? https://github.com/devongovett/node-wkhtmltopdf/pull/45/files#diff-8f3a57048f50333e0fecf7dd1c389638R83

**Comment by zxlin** [comment]
Oh hey, it is. 

Sorry, I was not very awake when looking at this.

**Pull request merged**
